#!/usr/bin/env python

# import argparse
import errno
import io
import os
import re
import subprocess
import sys
import json
import math
import copy

import neural_style as ns


def main():
    manifest = sys.argv[1]
    if sys.argv[1]:
        with open(sys.argv[1], "r") as manifest_file:
            manifest = json.load(manifest_file)

            args = [
                "--original_colors",
                "--model_weights",
                "datasets/imagenet-vgg-verydeep-19.mat",
                "--content_img",
                manifest["filename"],
                "--style_imgs",
                manifest["style_image"],
                "--max_iterations",
                str(manifest["max_iterations"]),
                "--device",
                "/gpu:0",
                "--content_weight",
                "10",
                "--style_weight",
                str(manifest["style_weight"]),
                "--max_size",
                "1400",
                "--img_name",
                os.path.splitext(manifest["filename_styled"])[0],
            ]
            ns.main(args)

            # for face in manifest["faces"]:
            #     args = [
            #         "--original_colors",
            #         "--model_weights",
            #         "datasets/imagenet-vgg-verydeep-19.mat",
            #         "--content_img",
            #         face["filename"],
            #         "--style_imgs",
            #         face["style_image"],
            #         "--max_iterations",
            #         str(face["max_iterations"]),
            #         "--device",
            #         "/gpu:0",
            #         "--content_weight",
            #         "10",
            #         "--style_weight",
            #         str(face["style_weight"]),
            #         "--max_size",
            #         "1000",
            #         "--img_name",
            #         os.path.splitext(face["filename_styled"])[0],
            #     ]
            #     ns.main(args)


main()
